# Generated by Django 3.1.3 on 2020-12-10 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('method', models.CharField(default='GET', max_length=30)),
                ('interval', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EndpointStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30, null=True)),
                ('status_code', models.CharField(max_length=30, null=True)),
                ('response_time', models.CharField(max_length=30, null=True)),
                ('last_updated', models.CharField(max_length=30, null=True)),
                ('down_from', models.CharField(max_length=30, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httpmonitor.endpoint')),
            ],
        ),
    ]
