# Generated by Django 3.1.3 on 2020-11-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='method',
            field=models.CharField(default='GET', max_length=30),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='response_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='status_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='endpointstatus',
            name='down_from',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='endpointstatus',
            name='last_updated',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='endpointstatus',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
